name: Deploy Laravel (Struktur Standar)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  web-deploy:
    name: üéâ Deploy ke Hosting
    runs-on: ubuntu-latest

    steps:
    # 1. Ambil kode dari repo
    - name: üöö Get latest code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Penting agar riwayat git terbaca lengkap

    # 2. Setup PHP
    - name: üêò Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' # Sesuaikan dengan PHP hosting Anda
        extensions: mbstring, intl, bcmath, gd

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Setting up file storage
      run: php artisan storage:link
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Generate key
      run: php artisan key:generate
    - name: Clear cache
      run: php artisan cache:clear
    - name: Configuration caching
      run: php artisan config:cache
    - name: Route caching
      run: php artisan route:cache
    - name: Clear view
      run: php artisan view:clear
    - name: Run Style Fixer
      run: ./vendor/bin/pint
    - name: Upload FTP Dev
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ SECRETS.FTP_DEV_HOST }}
        username: ${{ SECRETS.FTP_DEV_USER }}
        password: ${{ SECRETS.FTP_DEV_PASS }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/vendor/**
          **/.phpunit.cache/**
          **/storage/**
          .env
          bootstrap/cache/config.php
          public/hot
          public/storage
